### ISSUE TITLE
add capability to write out global regular (non-gaussian) lat/lon grid history files

### ISSUE THREAD

**Issue by jswhit** [NOAA-EMC/ufsatm#91] opened 2020-03-31 14:46 UTC
The 'gaussian_grid' option is used for backwards compatibility with the spectral GFS, for downstream applications (like GSI) that expect gaussian latitudes.  Most applications would prefer a regular evenly-spaced latitude grid.  Therefore, it makes sense to add a 'global_latlon' option for 'output_grid' in model_configure.

**Comment by jswhit2** [comment] 2020-03-31 14:52
@aerorahul

**Comment by jswhit2** [comment] 2020-03-31 19:50
@junwang-noaa pointed out that the 'latlon_grid' option was intended to provide this functionality, but was never fully implemented.  Right now it does not produce any output.  I've gone ahead and removed the non-functional 'latlon_grid' code from module_wrt_grid_comp.F90.

**Comment by jswhit2** [comment] 2020-03-31 19:52
@yangfanglin  asked how to define the resolution of the output grid.  The parameters `imo` and `jmo` can be used for this.  For example, `imo=2880 jmo=1440` will produce a 0.125 degree grid (not including the poles and equator).  `jmo=1441` will give you a 0.125 degree grid including the poles and equator.

**Comment by jswhit2** [comment] 2020-03-31 19:54
Currently, `netcdf` and `netcdf_parallel` output is supported in PR #92.  The structure of the resulting netcdf files are identical to the gaussian grid files (except that the latitude values are different).

**Comment by junwang-noaa** [comment] 2020-06-04 18:12
The code changes were merged to develop branch in PR #104. close ticket.

**Closed as completed by junwang-noaa** 2020-06-04 18:12 UTC
