### ISSUE TITLE
snow depth initialization error and remove unneaded code from ccpp and add protection for roughness length over ice

### ISSUE THREAD

**Issue by SMoorthi-emc** [NOAA-EMC/ufsatm#460] opened 2022-01-05 00:35 UTC
## Description
Provide a clear and concise description of what the bug is.
Also give a description of how to fix the bug.
Snow is initialized incorrectly for the case when land and water coexist (i.e. fractional grid) when the input contains only grid mean snow.

Also, there is some code in ccpp-physics that is not needed anymore and may add error if not removed (specifically for the uncoupled case).

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.
1. do this
2. then that
3. then, oops, look at the bug

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

## Output

**Screenshots**
If applicable, drag and drop screenshots to help explain your problem.

**output logs**
If applicable, include relevant output logs.
Either drag and drop the entire log file here (if a long log) or

```
paste the code here (if a short section of log)
```

## Testing:

1. Have you tested the code changes? On what platforms?

2. Have you run regression test in ufs-weather-model or ufs-s2s-model with code changes?
- Will the baseline results change? 
- If the baseline results change, is it expected? Please give brief explanation.

## Dependent PRs:

Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:

fv3atm pr: https://github.com/NOAA-EMC/fv3atm/pull/461

**Comment by junwang-noaa** [comment] 2022-01-25 04:00
The code was merged, the issue is closed.

**Closed as completed by junwang-noaa** 2022-01-25 04:00 UTC
Labels: bug
